# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

     steps:
    - uses: actions/checkout@v3
    - name: Set up Swift
      run: |
        brew install mint
        mint install swift@5.5

    - name: Build
      run: mint run swift build -v
    - name: Run tests
      run: mint run swift test -v